'use client';

import { useState } from 'react';
import { gqlFetch } from '@/lib/graphqlClient';

type Customer = { id: string; name: string; email: string; phone?: string | null; created_at: string };
export function CustomerInformationManager({ customer }: { customer: Customer }) {
  const [form, setForm] = useState({ name: customer.name, email: customer.email, phone: customer.phone || '' });
  const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(''); try { const token = localStorage.getItem('customer_token') || ''; await gqlFetch(`mutation($i: CustomerProfileInput!) { updateCustomerProfile(input: $i) { id name email phone } }`, { i: form }, token); setEditing(false); setMessage('Informasi akun berhasil diperbarui.'); } catch (e: any) { setMessage(e?.message || 'Gagal menyimpan informasi akun.'); } finally { setBusy(false); } }
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-bold text-slate-900">Informasi Akun</h2>{!editing && <button type="button" onClick={() => setEditing(true)} className="text-sm font-bold text-blue-600 hover:underline">Edit</button>}</div>{editing ? <form onSubmit={save} className="space-y-4"><label className="block text-sm font-semibold text-slate-700">Nama<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><label className="block text-sm font-semibold text-slate-700">Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><label className="block text-sm font-semibold text-slate-700">Nomor HP<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><div className="flex gap-2"><button disabled={busy} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy ? 'Menyimpan…' : 'Simpan'}</button><button type="button" onClick={() => setEditing(false)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Batal</button></div></form> : <div className="grid gap-5 sm:grid-cols-2"><div><div className="text-xs font-semibold uppercase text-slate-400">Nama</div><div className="mt-1 font-semibold text-slate-800">{form.name}</div></div><div><div className="text-xs font-semibold uppercase text-slate-400">Email</div><div className="mt-1 font-semibold text-slate-800">{form.email}</div></div><div><div className="text-xs font-semibold uppercase text-slate-400">Nomor HP</div><div className="mt-1 font-semibold text-slate-800">{form.phone || 'Belum diisi'}</div></div><div><div className="text-xs font-semibold uppercase text-slate-400">Member sejak</div><div className="mt-1 font-semibold text-slate-800">{new Date(customer.created_at).toLocaleDateString('id-ID')}</div></div></div>}{message && <p className="mt-4 text-sm font-medium text-emerald-600">{message}</p>}</section>;
}
