import Link from 'next/link';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { gqlFetchServer } from '@/lib/gql-server';
import { formatIDR } from '@/lib/cart';
import { CustomerAccountShell, type AccountCustomer } from '@/components/storefront/CustomerAccountShell';

export default async function CustomerAccountPage({ params }: { params: Promise<{ hash: string }> }) {
  const { hash } = await params; const token = (await cookies()).get('customer_token')?.value;
  if (!token) redirect(`/storefront/${hash}/sign-in?next=/storefront/${hash}/account`);
  const data = await gqlFetchServer<{ customerMe: (AccountCustomer & { orders: { id: string; order_number: string; status: string; total_amount: number; created_at: string; items: { id: string }[] }[] }) | null }>({ query: `query { customerMe { id name email phone created_at addresses { id label recipient phone address_line city province postal_code is_default } orders { id order_number status total_amount created_at items { id } } } }`, token });
  if (!data?.customerMe) redirect(`/storefront/${hash}/sign-in?next=/storefront/${hash}/account`); const c = data.customerMe;
  return <CustomerAccountShell hash={hash} customer={c} active="dashboard" title="Dashboard Akun" description="Selamat datang di area akun customer Anda."><div className="grid gap-5 md:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Informasi Akun</h2><p className="mt-2 text-sm text-slate-500">{c.name}<br />{c.email}<br />{c.phone || 'Nomor HP belum diisi'}</p><Link href={`/storefront/${hash}/account/information`} className="mt-4 inline-block text-sm font-bold text-blue-600 hover:underline">Kelola Informasi →</Link></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Address Book</h2><p className="mt-2 text-sm text-slate-500">{c.addresses.length ? `${c.addresses.length} alamat tersimpan` : 'Belum ada alamat tersimpan'}</p><Link href={`/storefront/${hash}/account/address-book`} className="mt-4 inline-block text-sm font-bold text-blue-600 hover:underline">Kelola Alamat →</Link></section></div><section className="mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Pesanan Terbaru</h2><Link href={`/storefront/${hash}/orders`} className="text-sm font-bold text-blue-600 hover:underline">Lihat semua</Link></div>{c.orders.length ? <div className="mt-4 space-y-3">{c.orders.slice(0, 3).map(o => <div key={o.id} className="flex justify-between rounded-xl border border-slate-100 p-3 text-sm"><div><b>{o.order_number}</b><div className="text-xs text-slate-500">{new Date(o.created_at).toLocaleDateString('id-ID')} · {o.items.length} item</div></div><div className="text-right"><div className="font-bold">{formatIDR(o.total_amount)}</div><Link href={`/storefront/${hash}/orders/${o.id}`} className="text-xs text-blue-600">Detail</Link></div></div>)}</div> : <p className="mt-4 text-sm text-slate-500">Belum ada pesanan.</p>}</section></CustomerAccountShell>;
}
